drop table if exists echomind_chat_messages;
drop table if exists echomind_chat_sessions;

create table echomind_chat_sessions (
    user_id varchar(128) not null default 'default',
    session_id varchar(128) not null,
    agent_id varchar(128),
    title varchar(255),
    summary longtext,
    message_count int not null default 0,
    created_at datetime(6) not null default current_timestamp(6),
    last_activity datetime(6) not null default current_timestamp(6),
    updated_at datetime(6) not null default current_timestamp(6),
    primary key (user_id, session_id)
);

create table echomind_chat_messages (
    id bigint generated by default as identity primary key,
    session_id varchar(128) not null,
    user_id varchar(128) not null default 'default',
    role varchar(32) not null,
    content longtext,
    timestamp datetime(6) not null,
    metadata_json longtext,
    attachments_json longtext,
    created_at datetime(6) not null default current_timestamp(6)
);
